apiVersion: batch/v1
kind: Job
metadata:
  name: job-creation
spec:
  template:
    spec:
      containers:
      - name: job-creation
        image: shahnavedali/create:1.0
        env:
        - name: MARIA_DB_HOST
          value: mariadb
        - name: ENV_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username 
        - name: ENV_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbname  
        - name: ENV_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbname 
      restartPolicy: Never
  backoffLimit: 4