apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: py-maria
spec:
  selector:
    matchLabels:
      tier: frontend
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: frontend
        app: mariadb
    spec:
      containers:
      - image: shahnavedali/valley:latest
        name: py-maria
        env:
        - name: ENV_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username 
        - name: ENV_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbname  
        - name: ENV_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbname 
        ports:
        - containerPort: 80
        
        